#ifndef _IMEID_H //guard
#define _IMEID_H

typedef unsigned long int ULong;

enum class ImeID : ULong {
	NONE,
	ID_IME_WRITE_COMPOSITION_CHARACTER,
	ID_IME_WRTIE_COMPLETE_CHARACTER,
	ID_IME_ERASE_COMPOSITION_CHARACTER,
	ID_IME_SET_COMPOSITION_OPTION,
	ID_IME_CONVERSION,
	ID_IME_OPEN_CANDIDATE,
	ID_IME_CLOSE_CANDIDATE,
	ID_IME_CONVERT_CHARACTER
};

#endif // !_IMEID_H
