#ifndef _APPID_H //guard
#define _APPID_H

typedef unsigned long int ULong;

enum class AppID : ULong
{
	NONE,
	ID_COMMAND_WRITE_AT_END,
	ID_COMMAND_INSERT_AT_CARET,
	ID_COMMAND_ERASE,
	ID_ACTION_NEW,
	ID_ACTION_NEW_WINDOW,
	ID_ACTION_OPEN,
	ID_ACTION_SAVE,
	ID_ACTION_SAVE_AS,
	ID_ACTION_CHANGE_FONT,
	ID_ACTION_AUTOWRAP,
	ID_ACTION_MOVE_UP,
	ID_ACTION_MOVE_DOWN,
	ID_ACTION_MOVE_LEFT,
	ID_ACTION_MOVE_RIGHT,
	ID_ACTION_MOVE_LINE_FRONT,
	ID_ACTION_MOVE_LINE_REAR,
	ID_ACTION_MOVE_WORD_LEFT,
	ID_ACTION_MOVE_WORD_RIGHT,
	ID_ACTION_MOVE_DOC_FRONT,
	ID_ACTION_MOVE_DOC_REAR,

};

#endif // !_APPID_H
