#ifndef _TIMERCONSTANTS_H //guard
#define _TIMERCONSTANTS_H
#include <afxwin.h>

static const UINT_PTR TIMER_ID_RESIZE_REFRESH = 1;
static const UINT_PTR TIMER_ID_AUTO_SCROLL = 2;
static const UINT_PTR TIMER_ID_LAZY_TRIM = 3;
static const UINT_PTR TIMER_ID_IME_OPEN_CANDIDATE = 4;
static const UINT_PTR TIMER_ID_IME_CLOSE_CANDIDATE = 5;
static const UINT RESIZE_REFRESH_INTERVAL = 75;
static const UINT AUTO_SCROLL_INTERVAL = 30;
static const UINT LAZY_TRIM_INTERVAL = 80;
static const UINT IME_OPEN_CANDIDATE_INTERVAL = 10;
static const UINT IME_CLOSE_CANDIDATE_INTERVAL = 10;

#endif // !_TIMERCONSTANTS_H
